### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by kucharzyk** [quarkiverse/quarkus-playwright#26]
quarks-playwright is working very well in my application - it's stable and not causing any issues.
But version 0.0.1 indicates its early stage of experimental plugin that might be not developed in the future.

Do you have any plans to mark it as stable and release version 1.0.0?

**Comment by kucharzyk** [comment]
This extension should be also published and visible on code.quarkus.io

**Comment by melloware** [comment]
@kucharzyk yep they were waiting on a Quarkus Core fix to allow this library to be published as a testing only library.

**Comment by melloware** [comment]
@ia3andy can this be listed on Extensions docs now have they fixed the issue with Test only components?  If so I can work on updating the Dev UI Card for this if it will also be able to listed in the DevUI as an extension?

**Comment by gastaldi** [comment]
@ia3andy why not transform this into an extension? Regardless if it's used only in testing, making it an extension would solve all the issues around tooling AFAIK

**Comment by ia3andy** [comment]
> @ia3andy why not transform this into an extension? Regardless if it's used only in testing, making it an extension would solve all the issues around tooling AFAIK

It's not possible, it won't compile, because of a restriction on dependencies

**Comment by melloware** [comment]
@all-contributors add @kucharzyk for testing

**Comment by melloware** [comment]
I have this working in this PR: https://github.com/quarkiverse/quarkus-playwright/pull/95  Playwright can be used in a normal app and not just for testing.   

Gonna see if I can make it work in Native Mode.
