### ISSUE TITLE
Allow for recording of test

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkiverse/quarkus-playwright#59]
Hello,

It would be amazing if there was a configuration option for recordings, and where to put them. Bonus points to be able to name recordings after the test name.

**Comment by ia3andy** [comment]
is it something available in Playwright?

**Comment by GregJohnStewart** [comment]
Yes! https://playwright.dev/java/docs/videos

**Comment by melloware** [comment]
This should be easy to add.

**Comment by melloware** [comment]
PR submitted.  Microsoft doesn't allow control over the names of the files.

**Comment by melloware** [comment]
@all-contributors add @GregJohnStewart for idea
