### ISSUE TITLE
Playwright in Quarkus Native (not for E2E testing)

### ISSUE THREAD

**Issue by thomaswiradikusuma** [quarkiverse/quarkus-playwright#68]
I understand that Quarkus supports Playwright for E2E testing, but I want to use it for web scraping. Specifically, I want to deploy Native Quarkus which uses Playwright to scrape websites.

Is this supported by this plugin? Does it work when compiled to Native?

**Comment by melloware** [comment]
I bet since its marked as a Test component its gets compiled out?  But go ahead and just try it and let us know?

**Comment by melloware** [comment]
@ia3andy mentioned here: https://github.com/quarkiverse/quarkus-playwright/issues/26#issuecomment-2122694441

> It's not possible, it won't compile, because of a restriction on dependencies

But i would like to verify?

**Comment by melloware** [comment]
@all-contributors add @thomaswiradikusuma for idea

**Comment by melloware** [comment]
OK I have it working as a runtime: https://github.com/quarkiverse/quarkus-playwright/pull/95

Next is trying to make it work in Native mode.

**Comment by thomaswiradikusuma** [comment]
@melloware I went to other direction (I use JavaScript and made it a micro service hehe), but I'll be happy to test this. I think wi

**Comment by melloware** [comment]
Ok got it working. Just waiting on some feedback from other devs before merging it.

**Comment by melloware** [comment]
@thomaswiradikusuma 2.0.0 is in Maven Central and I would love some feedback on your GraalVM testing to see if I missed anything.
